// Code generated by sqlc. moved, not edited (yet)
// versions:
//   sqlc v1.27.0

package dbo

import (
	"database/sql"
	"time"
)

func getStr(s sql.NullString) string {
	if s.Valid {
		return s.String
	}
	return ""
}

type Author struct {
	Authorid sql.NullInt64
	Name     string
	Url      sql.NullString
}

func (a *Author) StrUrl() string {
	return getStr(a.Url)
}

type ListAuthor struct {
	Author
	BookQty int
}

type Book struct {
	Bookid     sql.NullInt64
	Title      sql.NullString
	Format     string
	File       string
	Hash       string
	Updatets   time.Time
	Url        sql.NullString
	Isbn       sql.NullString
	CoverColor sql.NullString
	Edited     int32
	Hascover   int32
	CoverType  sql.NullString
	Authors    []Author
	Series     []BookSeries
	Tags       []Tag
	Blurb      sql.NullString
}

func (b *Book) StrUrl() string {
	return getStr(b.Url)
}
func (b *Book) StrIsbn() string {
	return getStr(b.Isbn)
}
func (b *Book) StrCoverColor() string {
	return getStr(b.CoverColor)
}
func (b *Book) StrCoverType() string {
	return getStr(b.CoverType)
}

type Series struct {
	SeriesId sql.NullInt64
	Title    string
	Url      sql.NullString
}

func (s *Series) StrUrl() string {
	return getStr(s.Url)
}

type BookSeries struct {
	Series
	Seqno sql.NullInt64
}

func (s *BookSeries) StrUrl() string {
	return getStr(s.Url)
}

type ListSeries struct {
	Series
	BookQty int
}

type Tag struct {
	TagId sql.NullInt64
	Name  string
	Color sql.NullString
}
