// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/scraper/": {
            "get": {
                "description": "The endpont give a processed url andpoint as a book",
                "produces": [
                    "application/json"
                ],
                "summary": "Scrape and process an url",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The url need to scrape",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ScraperResult"
                        }
                    }
                }
            }
        },
        "/author": {
            "get": {
                "description": "The endpont give back a list of authors with pagging, filtering information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "author"
                ],
                "summary": "Query for Authors metadata",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number, start with 1, default is 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "A query string used to filter authors based on their names.",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.AuthorResponse"
                        }
                    }
                }
            }
        },
        "/book": {
            "get": {
                "description": "The endpont give back a list of book metadata with pagging, filtering information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "Query for books metadata",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number, start with 1, default is 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "author ID used to filter books based on authors",
                        "name": "ai",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "series ID used to filter books based on series",
                        "name": "si",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "tag ID used to filter books based on tags",
                        "name": "ti",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "A query string used to filter books based on their description, title, author, series, and tags.",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BookResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Uopdate a book's metadata",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "Update a book",
                "parameters": [
                    {
                        "description": "Book to update",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Book"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/book/{bookId}": {
            "get": {
                "description": "The endpont give back the given book netadata",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "Get a book metadata",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the book",
                        "name": "bookId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Book"
                        }
                    },
                    "404": {
                        "description": "Book not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/export": {
            "get": {
                "description": "The endpont give back file for every ebook in the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "create a json file for all books in the system",
                "responses": {
                    "200": {
                        "description": "JSON file containing book list",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/query/author": {
            "get": {
                "description": "The endpont give back a list of authors for the given query string",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "author"
                ],
                "summary": "Query Authors for autocomplete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "A query string used to filter authors based on their names.",
                        "name": "query",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Suggestions"
                        }
                    }
                }
            }
        },
        "/query/tags": {
            "get": {
                "description": "The endpont give back a list of tags for the given query string",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Query Tags for autocomplete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "A query string used to filter tags based on their title.",
                        "name": "query",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Suggestions"
                        }
                    }
                }
            }
        },
        "/series": {
            "get": {
                "description": "The endpont give back a list of series with pagging, filtering information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "series"
                ],
                "summary": "Query for Series metadata",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number, start with 1, default is 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "A query string used to filter series based on their title/name.",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SeriesResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Author": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Id of the author",
                    "type": "integer"
                },
                "name": {
                    "description": "Name of the author",
                    "type": "string"
                },
                "url": {
                    "description": "external url of the author",
                    "type": "string"
                }
            }
        },
        "api.AuthorResponse": {
            "type": "object",
            "properties": {
                "filter": {
                    "description": "filter/query information",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Filter"
                    }
                },
                "pagination": {
                    "description": "list pagination",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.Pagination"
                        }
                    ]
                },
                "result": {
                    "description": "authors",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ListAuthor"
                    }
                }
            }
        },
        "api.Book": {
            "type": "object",
            "properties": {
                "authors": {
                    "description": "list of authors",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Author"
                    }
                },
                "blurb": {
                    "description": "blurb if the book",
                    "type": "string"
                },
                "coverColor": {
                    "description": "If has cover image, itas the avarage cover color",
                    "type": "string"
                },
                "coverType": {
                    "description": "cover filetype (if present cover image)",
                    "type": "string"
                },
                "edited": {
                    "description": "True if the metadata at least once has be saved (it will not overwriten by any automatic process)",
                    "type": "integer"
                },
                "file": {
                    "description": "file of the book",
                    "type": "string"
                },
                "fileType": {
                    "description": "type of the ebook: epub or mobipocket (prc, azw)",
                    "type": "string"
                },
                "hasCover": {
                    "description": "Book has cover image",
                    "type": "boolean"
                },
                "id": {
                    "description": "id of the book",
                    "type": "integer"
                },
                "series": {
                    "description": "list of series",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Series"
                    }
                },
                "tags": {
                    "description": "list of tags",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Tag"
                    }
                },
                "title": {
                    "description": "Title of the book (if present)",
                    "type": "string"
                },
                "url": {
                    "description": "external Url of the book",
                    "type": "string"
                }
            }
        },
        "api.BookResponse": {
            "type": "object",
            "properties": {
                "display": {
                    "description": "Extra display information",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.ExtraDisplay"
                        }
                    ]
                },
                "filter": {
                    "description": "filter/query information",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Filter"
                    }
                },
                "pagination": {
                    "description": "list pagination",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.Pagination"
                        }
                    ]
                },
                "result": {
                    "description": "list opf the books",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Book"
                    }
                }
            }
        },
        "api.ExtraDisplay": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "data for the filtering",
                    "type": "integer"
                },
                "type": {
                    "description": "type, description of extra information",
                    "type": "string"
                }
            }
        },
        "api.Filter": {
            "type": "object",
            "properties": {
                "type": {
                    "description": "type of the filter",
                    "type": "string"
                },
                "value": {
                    "description": "value of the filter",
                    "type": "string"
                }
            }
        },
        "api.ListAuthor": {
            "type": "object",
            "properties": {
                "books": {
                    "description": "book count of the author",
                    "type": "integer"
                },
                "id": {
                    "description": "Id of the author",
                    "type": "integer"
                },
                "name": {
                    "description": "Name of the author",
                    "type": "string"
                },
                "url": {
                    "description": "external url of the author",
                    "type": "string"
                }
            }
        },
        "api.ListSeries": {
            "type": "object",
            "properties": {
                "books": {
                    "description": "book count in this series",
                    "type": "integer"
                },
                "id": {
                    "description": "Id of the series",
                    "type": "integer"
                },
                "name": {
                    "description": "Name (title) of the series",
                    "type": "string"
                },
                "seqno": {
                    "description": "Book order in the series",
                    "type": "integer"
                },
                "url": {
                    "description": "external Url of the series",
                    "type": "string"
                }
            }
        },
        "api.Pagination": {
            "type": "object",
            "properties": {
                "base": {
                    "description": "bas url for reloding",
                    "type": "string"
                },
                "pages": {
                    "description": "number of tha pages",
                    "type": "integer"
                },
                "perPage": {
                    "description": "results per page",
                    "type": "integer"
                },
                "qty": {
                    "description": "number of the all results",
                    "type": "integer"
                },
                "selectedPage": {
                    "description": "selected, actual page number",
                    "type": "integer"
                }
            }
        },
        "api.ScraperAuthor": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "name of the author",
                    "type": "string"
                },
                "url": {
                    "description": "external Url",
                    "type": "string"
                }
            }
        },
        "api.ScraperResult": {
            "type": "object",
            "properties": {
                "authors": {
                    "description": "list of authors",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ScraperAuthor"
                    }
                },
                "blurb": {
                    "description": "blurb of the book",
                    "type": "string"
                },
                "series": {
                    "description": "list of the series",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ScraperSeries"
                    }
                },
                "tags": {
                    "description": "list of the tags",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "description": "title of the book",
                    "type": "string"
                }
            }
        },
        "api.ScraperSeries": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "name of the series",
                    "type": "string"
                },
                "seqno": {
                    "description": "book's position in the series",
                    "type": "string"
                },
                "url": {
                    "description": "external Url",
                    "type": "string"
                }
            }
        },
        "api.Series": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Id of the series",
                    "type": "integer"
                },
                "name": {
                    "description": "Name (title) of the series",
                    "type": "string"
                },
                "seqno": {
                    "description": "Book order in the series",
                    "type": "integer"
                },
                "url": {
                    "description": "external Url of the series",
                    "type": "string"
                }
            }
        },
        "api.SeriesResponse": {
            "type": "object",
            "properties": {
                "filter": {
                    "description": "filter/query information",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Filter"
                    }
                },
                "pagination": {
                    "description": "list pagination",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.Pagination"
                        }
                    ]
                },
                "result": {
                    "description": "Series",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ListSeries"
                    }
                }
            }
        },
        "api.SuggestionData": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "id of the data",
                    "type": "integer"
                },
                "name": {
                    "description": "Text of the data",
                    "type": "string"
                },
                "url": {
                    "description": "url of the data",
                    "type": "string"
                }
            }
        },
        "api.SuggestionItem": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "data for processing",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.SuggestionData"
                        }
                    ]
                },
                "value": {
                    "description": "display text",
                    "type": "string"
                }
            }
        },
        "api.Suggestions": {
            "type": "object",
            "properties": {
                "query": {
                    "description": "query string",
                    "type": "string"
                },
                "suggestions": {
                    "description": "result list",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.SuggestionItem"
                    }
                }
            }
        },
        "api.Tag": {
            "type": "object",
            "properties": {
                "color": {
                    "description": "Color of the tag",
                    "type": "string"
                },
                "id": {
                    "description": "id fo the tag",
                    "type": "integer"
                },
                "name": {
                    "description": "name of the tag",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "none": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8888",
	BasePath:         "/api/",
	Schemes:          []string{},
	Title:            "eBook library API",
	Description:      "Query/edit eBook metadata",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
